MaSuper-Agence/src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{

    const HEAT = [
        0=>'Electrique',
        1=>'Gaz'
    ];

    public function __construct()
    {
        $this->setCreateAt(new \DateTime());
    }
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    { 
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        $slugify = (new Slugify())->slugify($this->title);
        return $slugify;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->getPrice(), 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType(): ?string
    {

        return self::HEAT[$this->heat];
    }
    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }
}

MaSuper-Agence/src/Controller/HelloWorldController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HelloWorldController
{
    /**
     * @Route("/hello")
     */
    public function getHelloWorld(Request $request)
    {
        $name = $request->get('name');

        return new Response('Hello '.$name.'!');
    }

}

MaSuper-Agence/src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     * @param PropertyRepository $repository
     * @return Response
     */
    public function index(PropertyRepository $repository): Response
    {
        $properties = $repository->findLatest();
        return $this->render('pages/home.html.twig', [
            'properties' => $properties
        ]);
    }
}

MaSuper-Agence/src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{

    private $repository;
    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/lesbiens", name="property.index")
     */
    public function index(): Response
    {
        //$property = $this->repository->findAllVisible();
        //$property[0]->setSold(false);
        //$this->em->flush();
        /*
        $property = new Property();

        $property->setTitle('Mon premier bien')->setPrice(200000)->setRooms(4)->setBedrooms(3)->setDescription("Une petite descriptipon")
        ->setFloor(4)->setSurface(60)->setHeat(1)->setCity('Montpellier')->setAddress('15 Boulevard Gambetta')
        ->setPostalCode(34000);

        $em = $this->getDoctrine()->getManager();
        $em->persist($property);
        $em->flush();
        */



        return $this->render('property/index.html.twig',['current_menu' => 'properties']);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug":"[a-z0-9\-]*"})
     * @return Response
     */
    //public function show($slug, $id): Response
    public function show(Property $property, string $slug): Response
    {
        if($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show', [
                    'id'=>$property->getId(),
                    'slug'=>$property->getSlug()
            ], 301);
        }
        //$property = $this->repository->find($id);
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties'
        ]);
    }

}

MaSuper-Agence/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{{ path ('home')}}">Mon agence</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="{{ path ('home')}}" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link {%if current_menu is defined and current_menu == 'properties'%} active {% endif %}" href="{{ path('property.index')}}">Acheter</a>
      </li>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>        
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    </body>
</html>

MaSuper-Agence/templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title 'Mon Agence' %}

{% block body %}
    <div class="jumbotron text-center">
        <h1>Agence de Norbert</h1>
        <p>blah blah</p>
    </div>
    <div class="container">
    <h2>Les derniers biens</h2>
        <div class "row  flex">
            {% for property in properties %}
            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href='{{ path('property.show', {id:property.id, slug:property.slug})}}'>{{ property.title }}</a>
                        </h5>
                        <p class="card-text">{{ property.city }}({{ property.postalCode }})</p>
                        <div class="text-primary" style="font-weigth:bold;font-size:2rem;">{{ property.formattedPrice }} € </div>
                    </div>
                </div>
            </div>
    
            {% endfor %}
        </div>
    </div>
{% endblock %}

MaSuper-Agence/templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos biens' %}

{% block body %}
<div class="container mt-4"  >
    <h1>Voir tous nos biens</h1>
</div>
{% endblock %}

MaSuper-Agence/templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}

<div class="jumbotron">
    <div class="row">
        <div class="col md-8">

        </div>
        <div class="col md-4">
            <h1>{{ property.title }}</h1>
            <h2>{{ property.rooms }} pièces - {{ property.surface }}  m2</h2>
            <div class="text-primary" style="font-size: 4rem;font-weight: bold;">{{ property.formattedPrice}} € </div>
            <a href="#" class "btn btn-primary"> Contacter l'agence</a>
        </div>
    </div>
</div>

<div class="container mt-4">

    <nav class="nav nav-tabs" id="tab">
    </nav>
    <p>
        {{ property.description | nl2br}}
    </p>
    <div class="row">
        <div class="col md-8">
            <h2>Caractéristiques</h2>
            <table class="table table-striped">
            <tr>
                <td>Surface habitable</td>
                <td>{{ property.surface }} m2</td>
            </tr>
            <tr>
                <td>Nombre de pièces</td>
                <td>{{ property.rooms }}</td>
            </tr>
            <tr>
                <td>Nombre de chambres</td>
                <td>{{ property.bedrooms }}</td>
            </tr>
            <tr>
                <td>Etage</td>
                <td>{{ property.floor }}</td>
            </tr>
            <tr>
                <td>Chauffage</td>
                <td>{{ property.heatType }}</td>
            </tr>

            </table>
        </div>
        <div class="col md-4">
            <h2>Spécificités</h2>
        </div>
    </div>



{% endblock %}